channels:
  - conda-forge
  - anaconda
dependencies:
  # - cmake  ## Only install on demand.
  - python<3.10
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - tqdm
    - fire
    - seaborn
    - palettable
    - wandb
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - torch
    - torchvision
    - gpytorch
